language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.10
    - python: "3.3"
      env: DJANGO_VERSION=1.4.10
install:
  - pip install -q Django==${DJANGO_VERSION} --use-mirrors
  - pip install -q -e . -r requirements-test.txt --use-mirrors
  - pip install coveralls --use-mirrors
before_script:
  - make lint
script:
  - make coverage
after_success:
  - coveralls
