language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django21
    - env: TOXENV=flake8

install:
  - pip install tox

script:
  - tox -v
